version: "3.9"
services:
  jenkins:
    container_name: jenkins
    image: thanhngan/jenkins
    build:
      context: .
      dockerfile: jenkins.Dockerfile
      tags:
        - "thanhngan/jenkins:2.401.3-lts-jdk11"
    ports:
      - 8080:8080
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
  dind:
    container_name: docker
    image: docker:dind
    privileged: true
    ports:
      - 2376:2376
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins: